# Generated by Django 2.0.2 on 2018-02-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deploys',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('sha', models.CharField(blank=True, max_length=40, null=True)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=8, null=True)),
                ('engineer', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'deploys',
                'managed': False,
            },
        ),
    ]
